In [14]:
import pandas as pd
import requests
pd.set_option('display.max_columns', None) # We can see all columns in a wide Dataframe
import time
import numpy as np

In [15]:
test_url = "https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season=2013-14&SeasonType=Regular%20Season&StatCategory=PTS"

In [16]:
r = requests.get(url=test_url).json()

In [17]:
table_headers = r['resultSet']['headers']

In [18]:
pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,201142,1,Kevin Durant,1610612760,OKC,81,3122,849,1688,0.503,192,491,0.391,703,805,0.873,58,540,598,445,103,59,285,174,2593,2572,1.56,0.36
1,2546,2,Carmelo Anthony,1610612752,NYK,77,2982,743,1643,0.452,167,415,0.402,459,541,0.848,145,477,622,242,95,51,198,224,2112,1942,1.22,0.48
2,2544,3,LeBron James,1610612748,MIA,77,2902,767,1353,0.567,116,306,0.379,439,585,0.750,81,452,533,488,121,26,270,126,2089,2255,1.81,0.45
3,201567,4,Kevin Love,1610612750,MIN,77,2797,650,1421,0.457,190,505,0.376,520,633,0.821,224,739,963,341,59,35,196,136,2010,2328,1.74,0.30
4,201933,5,Blake Griffin,1610612746,LAC,80,2863,718,1359,0.528,12,44,0.273,482,674,0.715,192,565,757,309,92,51,224,265,1930,2082,1.38,0.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477,202354,475,Dexter Pittman,1610612737,ATL,2,3,0,1,0.000,0,0,0.000,0,2,0.000,3,0,3,0,0,0,0,0,0,0,0.00,0.00
478,203548,475,Elias Harris,1610612747,LAL,2,11,0,1,0.000,0,0,0.000,0,0,0.000,1,0,1,1,1,0,0,0,0,2,0.00,0.00
479,2735,475,Josh Childress,1610612740,NOP,4,24,0,0,0.000,0,0,0.000,0,0,0.000,0,3,3,2,1,0,1,1,0,5,2.00,1.00
480,2767,475,Royal Ivey,1610612760,OKC,2,5,0,2,0.000,0,1,0.000,0,0,0.000,0,1,1,0,0,0,0,1,0,-1,0.00,0.00
481,203091,475,Royce White,1610612758,SAC,3,9,0,1,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,2,0,-1,0.00,0.00

In [19]:
temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)
temp_df2 = pd.DataFrame({'Year' : ['2014-15' for i in range(len(temp_df1))],
                         'Season_type' : ['Regular%20Season' for i in range(len(temp_df1))]})
temp_df3 = pd.concat([temp_df2,temp_df1], axis=1)
temp_df3

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,2014-15,Regular%20Season,201142,1,Kevin Durant,1610612760,OKC,81,3122,849,1688,0.503,192,491,0.391,703,805,0.873,58,540,598,445,103,59,285,174,2593,2572,1.56,0.36
1,2014-15,Regular%20Season,2546,2,Carmelo Anthony,1610612752,NYK,77,2982,743,1643,0.452,167,415,0.402,459,541,0.848,145,477,622,242,95,51,198,224,2112,1942,1.22,0.48
2,2014-15,Regular%20Season,2544,3,LeBron James,1610612748,MIA,77,2902,767,1353,0.567,116,306,0.379,439,585,0.750,81,452,533,488,121,26,270,126,2089,2255,1.81,0.45
3,2014-15,Regular%20Season,201567,4,Kevin Love,1610612750,MIN,77,2797,650,1421,0.457,190,505,0.376,520,633,0.821,224,739,963,341,59,35,196,136,2010,2328,1.74,0.30
4,2014-15,Regular%20Season,201933,5,Blake Griffin,1610612746,LAC,80,2863,718,1359,0.528,12,44,0.273,482,674,0.715,192,565,757,309,92,51,224,265,1930,2082,1.38,0.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477,2014-15,Regular%20Season,202354,475,Dexter Pittman,1610612737,ATL,2,3,0,1,0.000,0,0,0.000,0,2,0.000,3,0,3,0,0,0,0,0,0,0,0.00,0.00
478,2014-15,Regular%20Season,203548,475,Elias Harris,1610612747,LAL,2,11,0,1,0.000,0,0,0.000,0,0,0.000,1,0,1,1,1,0,0,0,0,2,0.00,0.00
479,2014-15,Regular%20Season,2735,475,Josh Childress,1610612740,NOP,4,24,0,0,0.000,0,0,0.000,0,0,0.000,0,3,3,2,1,0,1,1,0,5,2.00,1.00
480,2014-15,Regular%20Season,2767,475,Royal Ivey,1610612760,OKC,2,5,0,2,0.000,0,1,0.000,0,0,0.000,0,1,1,0,0,0,0,1,0,-1,0.00,0.00
481,2014-15,Regular%20Season,203091,475,Royce White,1610612758,SAC,3,9,0,1,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,2,0,-1,0.00,0.00

In [20]:
del temp_df1,temp_df2,temp_df3

In [21]:
df_cols = ['Year' , 'Season_type'] + table_headers

In [22]:
pd.DataFrame(columns=df_cols)

Empty DataFrame
Columns: [Year, Season_type, PLAYER_ID, RANK, PLAYER, TEAM_ID, TEAM, GP, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PTS, EFF, AST_TOV, STL_TOV]
Index: []

In [23]:
headers = {
    "Accept": "*/*",
    "Accept-Encoding":"gzip, deflate, br, zstd",
    "Accept-Language":"tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7",
    "Connection":"keep-alive",
    "Host":"stats.nba.com",
    "Origin":"https://www.nba.com",
    "Referer":"https://www.nba.com/",
    "Sec-Ch-Ua":'"Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"',
    "Sec-Ch-Ua-Mobile":"?0",
    "Sec-Ch-Ua-Platform":'"Windows"',
    "Sec-Fetch-Dest":"empty",
    "Sec-Fetch-Mode":"cors",
    "Sec-Fetch-Site":"same-site",
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
}

In [24]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\murat\appdata\local\programs\python\python312\lib\site-packages (3.1.3)
Requirement already satisfied: et-xmlfile in c:\users\murat\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [25]:
df = pd.DataFrame(columns=df_cols)

season_types = ['Regular%20Season', 'Playoffs']
years = ['2014-15' ,'2015-16' ,'2016-17' ,'2017-18' ,'2018-19' ,'2019-20' ,'2020-21' ,'2021-22' ,'2022-23' ,'2023-24' ]

begin_loop = time.time()
for y in years:
    for s in season_types:
        api_url ='https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season='+y+'&SeasonType='+s+'&StatCategory=PTS'
        r = requests.get(url=api_url).json()
        temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)
        temp_df2 = pd.DataFrame({'Year' : [y for i in range(len(temp_df1))],
                                'Season_type' : [s for i in range(len(temp_df1))]})
        temp_df3 = pd.concat([temp_df2,temp_df1], axis=1)
        df = pd.concat([df,temp_df3], axis=0)
        print(f'Finished scraping data from the {y} {s}')
        lag = np.random.uniform(low=20, high=40)
        print(f'...waiting {round(lag,1)} seconds...')
        time.sleep(lag)

print(f'Process completed!! Total run time: {round((time.time()-begin_loop) / 60,2)}')
df.to_excel("nba_player_data.xlsx", index=False)

C:\Users\murat\AppData\Local\Temp\ipykernel_20084\1513270642.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df,temp_df3], axis=0)

Finished scraping data from the 2014-15 Regular%20Season
...waiting 26.9 seconds...
Finished scraping data from the 2014-15 Playoffs
...waiting 34.9 seconds...
Finished scraping data from the 2015-16 Regular%20Season
...waiting 26.7 seconds...
Finished scraping data from the 2015-16 Playoffs
...waiting 27.7 seconds...
Finished scraping data from the 2016-17 Regular%20Season
...waiting 31.5 seconds...
Finished scraping data from the 2016-17 Playoffs
...waiting 32.5 seconds...
Finished scraping data from the 2017-18 Regular%20Season
...waiting 28.4 seconds...
Finished scraping data from the 2017-18 Playoffs
...waiting 20.7 seconds...
Finished scraping data from the 2018-19 Regular%20Season
...waiting 21.8 seconds...
Finished scraping data from the 2018-19 Playoffs
...waiting 30.9 seconds...
Finished scraping data from the 2019-20 Regular%20Season
...waiting 39.1 seconds...
Finished scraping data from the 2019-20 Playoffs
...waiting 28.2 seconds...
Finished scraping data from the 2020-21 Regular%20Season
...waiting 20.6 seconds...
Finished scraping data from the 2020-21 Playoffs
...waiting 29.5 seconds...
Finished scraping data from the 2021-22 Regular%20Season
...waiting 40.0 seconds...
Finished scraping data from the 2021-22 Playoffs
...waiting 35.5 seconds...
Finished scraping data from the 2022-23 Regular%20Season
...waiting 24.1 seconds...
Finished scraping data from the 2022-23 Playoffs
...waiting 23.4 seconds...
Finished scraping data from the 2023-24 Regular%20Season
...waiting 31.3 seconds...
Finished scraping data from the 2023-24 Playoffs
...waiting 36.0 seconds...
Process completed!! Total run time: 10.09

In [26]:
df

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,2014-15,Regular%20Season,201935,1,James Harden,1610612745,HOU,81,2981,647,1470,0.440,208,555,0.375,715,824,0.868,75,384,459,565,154,60,321,208,2217,2202,1.76,0.48
1,2014-15,Regular%20Season,201939,2,Stephen Curry,1610612744,GSW,80,2613,653,1341,0.487,286,646,0.443,308,337,0.914,56,285,341,619,163,16,249,158,1900,2073,2.49,0.66
2,2014-15,Regular%20Season,201566,3,Russell Westbrook,1610612760,OKC,67,2302,627,1471,0.426,86,288,0.299,546,654,0.835,124,364,488,574,140,14,293,184,1886,1857,1.96,0.48
3,2014-15,Regular%20Season,2544,4,LeBron James,1610612739,CLE,69,2493,624,1279,0.488,120,339,0.354,375,528,0.710,51,365,416,511,109,49,272,135,1743,1748,1.88,0.40
4,2014-15,Regular%20Season,203081,5,Damian Lillard,1610612757,POR,82,2925,590,1360,0.434,196,572,0.343,344,398,0.864,49,329,378,507,97,21,222,164,1720,1677,2.28,0.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,2023-24,Playoffs,1641765,197,Olivier-Maxence Prosper,1610612742,DAL,1,1,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
209,2023-24,Playoffs,1631115,197,Orlando Robinson,1610612748,MIA,1,2,0,1,0.000,0,1,0.000,0,0,0.000,0,1,1,1,0,0,0,0,0,1,0.00,0.00
210,2023-24,Playoffs,203933,197,T.J. Warren,1610612750,MIN,3,11,0,2,0.000,0,1,0.000,0,0,0.000,2,1,3,1,0,0,0,0,0,2,0.00,0.00
211,2023-24,Playoffs,201152,197,Thaddeus Young,1610612756,PHX,1,4,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
212,2023-24,Playoffs,203648,197,Thanasis Antetokounmpo,1610612749,MIL,2,5,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,1,1,0,1,0,2,0.00,0.00